name: Download M3U8 Video

on:
  workflow_dispatch:
    inputs:
      m3u8_url:
        description: 'Nhập link .m3u8 cần tải'
        required: true
        default: ''

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Cài yt-dlp và ffmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          pip install -U yt-dlp

      - name: Tải video từ link
        run: |
          yt-dlp "${{ github.event.inputs.m3u8_url }}" -o output.mp4 --no-part

      - name: Upload video kết quả
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-video
          path: output.mp4
